### ISSUE TITLE
Server Crash on Load

### ISSUE THREAD

**Issue by WenXin20** [bl4ckscor3/ChanceGlobe#12] opened 2020-04-10 23:28 UTC
`Minecraft v1.15.2`
`Forge v31.1.39`
`Chance Globe v1.3.3`

The first time I loaded the server it loaded just fine, but after that the server crashes with each load.
[Crash Report](https://gist.github.com/WenXin20/e6a8f2f7b61bd0e2233884aef989518f)

**Comment by bl4ckscor3** [comment] 2020-04-11 09:39
Can you please post your latest.log?

**Comment by WenXin20** [comment] 2020-04-11 16:06
Sure!
https://gist.github.com/WenXin20/f0d1151cf3e5898e04ea7e77f5f16ff0

**Comment by bl4ckscor3** [comment] 2020-04-11 16:40
Thanks! Please try out this version https://www.curseforge.com/minecraft/mc-mods/chance-globe/files/2927288

**Comment by WenXin20** [comment] 2020-04-12 00:09
After a bit of testing, it still seems to crash after the 1st time loading: https://gist.github.com/WenXin20/8e3335d81efcb9cd2b18baa06364848a

**Comment by bl4ckscor3** [comment] 2020-04-12 09:18
Ok. I uploaded a new version, please try it out. While I do have an understanding of the crashes, this will basically go on like this as I can't reproduce them. https://www.curseforge.com/minecraft/mc-mods/chance-globe/files/2927939

EDIT: Did not mean to close this.

**Comment by bl4ckscor3** [comment] 2020-04-25 11:20
This seems to be resolved.

**Comment by WenXin20** [comment] 2020-04-25 13:53
Oh sorry, I've been pretty busy with school. But I'll let you know once I'm able to try it out.

**Comment by WenXin20** [comment] 2021-04-20 08:09
Hello, apologies for not getting back on this! I'm now using `v1.16.5` with `Forge v36.1.4`, but I am still getting the exact same crash. 

But something that I have figured out is that the crash only happens after the config file is generated, deleting the config file fixes the crash temporarily. And then if I disable the blacklist in the config, the crash stops completely so far.

**Comment by bl4ckscor3** [comment] 2021-04-20 09:17
Can you post an updated crash report please?

**Comment by WenXin20** [comment] 2021-04-20 15:58
Yep, here is is: https://gist.github.com/WenXin20/546807641635deb50577b21876c7d0f0#file-chance_globe_crash-txt-L44

**Comment by bl4ckscor3** [comment] 2021-04-20 17:16
Thanks, appreciate it! Updated the mod, third time's the charm? Please do report back if it helps. https://www.curseforge.com/minecraft/mc-mods/chance-globe/files/3283319 (New link, only changes are in the mods.toml file. They are not relevant to this issue)

**Comment by WenXin20** [comment] 2021-04-20 22:48
So far so good. :)

**Closed as completed** 2021-05-11 13:27 UTC
